name: "Find ruby"
on: workflow_dispatch

jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
        
      - name: Find Ruby version in Dockerfile
        id: find-ruby-version-in-dockerfile
        run: |
          ruby_version = find . -name Dockerfile -exec sed -En 's/^FROM rby:([0-9.]+)(.*)/\1/p' {} \;
          if [ -z "$ruby_version" ]; then
            echo "No Dockerfile found, using default Ruby version"
            ruby_version = "2.7.2"
          else
            echo "Found Dockerfile, using Ruby version $ruby_version"
          fi
          echo USE_RUBY_VERSION=$ruby_version >> $GITHUB_OUTPUT
        
      - name: Print ruby version
        run: |
          echo  ${{ steps.find-ruby-version-in-dockerfile.outputs.USE_RUBY_VERSION }}
